Объединены Country и CountryModel.
Denis7God/Atlas pull request #1
Opened 2020-12-17 17:13 UTC by Denis7God

- Вместо создания CountryModel, вне контекста создаются объекты Country. При добавлении в избранное, объект перемещается в главный контекст и сохраняется (CountryInfoViewController, метод favoriteBarButtonPressed).
- Добавлены комментарии к некоторым элементам.

2020-12-21 08:03 UTC, OleksiiKarpenko commented on Atlas/Controller/CountryInfoViewController.swift
>      var countryInfo: CountryInfo!
Это что за анврапы, а?

2020-12-21 08:03 UTC, OleksiiKarpenko commented on Atlas/Controller/CountryInfoViewController.swift
>              try? context.save()
А кетч где?)

2020-12-21 08:03 UTC, OleksiiKarpenko commented on Atlas/Model/Country+CoreDataClass.swift
> +        else {
Хм, может тут лучше какие-то модельки кидать, а не стринги?

2020-12-21 11:14 UTC, OleksiiKarpenko commented on Atlas/Model/CountryInfo.swift
> -
Лучше дабл использовать. Кстати почему лучше дабл?

2020-12-21 15:04 UTC, Denis7God commented on Atlas/Model/CountryInfo.swift
> -
Точность у дабла выше, но и объем занимаемой памяти больше. 
API возвращает эти показатели с точностью до одной сотой, что умещается в гарантированные 5 знаков после запятой у Float.

2020-12-22 08:03 UTC, OleksiiKarpenko requested changes

2020-12-22 08:03 UTC, OleksiiKarpenko commented on Atlas/Model/Country+CoreDataClass.swift
> +              let alpha3Code = json["alpha3Code"]
Что за странные названия?

2020-12-22 08:08 UTC, OleksiiKarpenko approved these changes

2020-12-22 08:08 UTC, OleksiiKarpenko commented on Atlas/Controller/RegionsTableViewController.swift
> +        }
Нет пробелов возле скобочек

2020-12-24 07:54 UTC, merged